### ISSUE TITLE
TASK [Check Symbol node health] で fail

### ISSUE THREAD

**Issue by chirolyn** [koutyan/Symbol-Node-Builder#1]
初めまして。ツールを使用させていただいております。素敵なツールを公開していただきありがとうございます。

何度か試しておりますが、どうしても手順４がうまくいかず、下記のようなエラーが出てしまい、困っています。
お忙しいところ恐縮ですが、対処法をご教示いただけたらと思います。
よろしくお願いいたします。

TASK [Check Symbol node health] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "{\"status\":{\"apiNode\":\"down\",\"db\":\"up\"}}", "content_length": "39", "content_type": "application/json", "date": "Sun, 06 Feb 2022 00:30:29 GMT", "elapsed": 0, "failed_when_result": true, "json": {"status": {"apiNode": "down", "db": "up"}}, "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "status": 503, "url": "http://×××.×××.×××.×××:3000/node/health"}

PLAY RECAP *********************************************************************
localhost                  : ok=29   changed=23   unreachable=0    failed=1    skipped=1    rescued=0    ignored=2

環境ですが、VPSを使用しており、仮想8コア、SSD800GB、メモリ16GBとなっております。

**Comment by koutyan** [comment]
symbol-server コンテナの一部が正常に起動していない可能性が高いです。

`docker ps -a` コマンドの実行結果および当ツール実行時の全ログ(エラーが出た箇所以外のものも含む)を添付いただけますでしょうか。
(これらを添付いただければ何かご助言することが可能かもしれません)

以上、よろしくお願いいたします。

**Comment by chirolyn** [comment]
お忙しい中ご回答ありがとうございます。

全ログとコマンド実行結果を添付いたします。
よろしくお願いいたします。
[全ログ.txt](https://github.com/koutyan/Symbol-Node-Builder/files/8013451/default.txt)
[コマンド実行結果.txt](https://github.com/koutyan/Symbol-Node-Builder/files/8013454/default.txt)
